# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'EcoRangerWildLifeExplorer' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    fmt_target = installer.pods_project.targets.find { |target| target.name == 'fmt' }
    if fmt_target
      fmt_target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end

    ['base.h', 'core.h'].each do |header_name|
      fmt_header = File.join(installer.sandbox.root.to_s, 'fmt', 'include', 'fmt', header_name)
      next unless File.exist?(fmt_header)

      text = File.read(fmt_header)
      updated = text
        .gsub(/(#elif defined\(__cpp_consteval\)\n#\s*define FMT_USE_CONSTEVAL) 1/, '\\1 0')
        .gsub(/(#elif FMT_GCC_VERSION >= 1002 \|\| FMT_CLANG_VERSION >= 1101\n#\s*define FMT_USE_CONSTEVAL) 1/, '\\1 0')
      if updated != text
        File.chmod(0o644, fmt_header)
        File.write(fmt_header, updated)
      end
    end
  end
end
