import type {ImageSourcePropType} from 'react-native';

export const images = {
  loaderBackground: require('./images/loader-background.png') as ImageSourcePropType,
  onboardingSavanna: require('./images/onboarding-savanna.png') as ImageSourcePropType,
  onboardingCards: {
    places: require('./images/onboarding-card-places.png') as ImageSourcePropType,
    animals: require('./images/onboarding-card-animals.png') as ImageSourcePropType,
    learn: require('./images/onboarding-card-learn.png') as ImageSourcePropType,
  },
  rangers: {
    leo: require('./images/ranger-leo.png') as ImageSourcePropType,
    ella: require('./images/ranger-ella.png') as ImageSourcePropType,
    chee: require('./images/ranger-chee.png') as ImageSourcePropType,
    koda: require('./images/ranger-koda.png') as ImageSourcePropType,
  },
  parks: {
    serengeti: require('./images/park-serengeti.png') as ImageSourcePropType,
    kruger: require('./images/park-kruger.png') as ImageSourcePropType,
    yellowstone: require('./images/park-yellowstone.png') as ImageSourcePropType,
    galapagos: require('./images/park-galapagos.png') as ImageSourcePropType,
    banff: require('./images/park-banff.png') as ImageSourcePropType,
    komodo: require('./images/park-komodo.png') as ImageSourcePropType,
    kaziranga: require('./images/park-kaziranga.png') as ImageSourcePropType,
    fiordland: require('./images/park-fiordland.png') as ImageSourcePropType,
    torresDelPaine: require('./images/park-torres-del-paine.png') as ImageSourcePropType,
    etosha: require('./images/park-etosha.png') as ImageSourcePropType,
    ranthambore: require('./images/park-ranthambore.png') as ImageSourcePropType,
    denali: require('./images/park-denali.png') as ImageSourcePropType,
    chobe: require('./images/park-chobe.png') as ImageSourcePropType,
    bialowieza: require('./images/park-bialowieza.png') as ImageSourcePropType,
    kakadu: require('./images/park-kakadu.png') as ImageSourcePropType,
    everglades: require('./images/park-everglades.png') as ImageSourcePropType,
    bwindi: require('./images/park-bwindi.png') as ImageSourcePropType,
    greatBarrierReef: require('./images/park-great-barrier-reef.png') as ImageSourcePropType,
    arenal: require('./images/park-arenal.png') as ImageSourcePropType,
    addo: require('./images/park-addo.png') as ImageSourcePropType,
    sumatranRhino: require('./images/park-sumatran-rhino.png') as ImageSourcePropType,
    canaima: require('./images/park-canaima.png') as ImageSourcePropType,
    svalbard: require('./images/park-svalbard.png') as ImageSourcePropType,
    pantanal: require('./images/park-pantanal.png') as ImageSourcePropType,
  },
  animals: {
    africanLion: require('./images/animal-african-lion.png') as ImageSourcePropType,
    africanElephant: require('./images/animal-african-elephant.png') as ImageSourcePropType,
    cheetah: require('./images/animal-cheetah.png') as ImageSourcePropType,
    zebra: require('./images/animal-zebra.png') as ImageSourcePropType,
    giraffe: require('./images/animal-giraffe.png') as ImageSourcePropType,
    bengalTiger: require('./images/animal-bengal-tiger.png') as ImageSourcePropType,
    grayWolf: require('./images/animal-gray-wolf.png') as ImageSourcePropType,
    polarBear: require('./images/animal-polar-bear.png') as ImageSourcePropType,
    giantPanda: require('./images/animal-giant-panda.png') as ImageSourcePropType,
    komodoDragon: require('./images/animal-komodo-dragon.png') as ImageSourcePropType,
    galapagosTortoise: require('./images/animal-galapagos-tortoise.png') as ImageSourcePropType,
    baldEagle: require('./images/animal-bald-eagle.png') as ImageSourcePropType,
    greenSeaTurtle: require('./images/animal-green-sea-turtle.png') as ImageSourcePropType,
    redEyedTreeFrog: require('./images/animal-red-eyed-tree-frog.png') as ImageSourcePropType,
    snowLeopard: require('./images/animal-snow-leopard.png') as ImageSourcePropType,
    orangutan: require('./images/animal-orangutan.png') as ImageSourcePropType,
  },
};
